In [ ]:
# Setup the google colab
!pip install xmnlp

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [2]:
# googlePath = "./drive/MyDrive/L101Project/"
googlePath = "./"

In [3]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import Session

config = ConfigProto()
config.gpu_options.allow_growth = True
session = Session(config=config)
tf.compat.v1.disable_eager_execution()


In [5]:
import csv
import numpy as np

import collections
import operator
from functools import reduce
import json
from multiprocessing import Pool
from keras.preprocessing.sequence import pad_sequences

In [6]:
import xmnlp
xmnlp.radical('花丸晴琉')

(Lazy Load) Loading model...


['艹', '丿', '日', '王']

In [7]:
# Build up Chinese sub-character unites diactionary.
chaiZi_Dic = {}
with open(googlePath + "corpus/chaizi/chaizi-jt.txt", 'r') as f:
    reader = csv.reader(f,delimiter='\t')
    for row in reader:
        chaiZi_Dic[row[0]] = row[1]
        
def getSubChar(charCN):
    if(charCN in chaiZi_Dic.keys()):
        return chaiZi_Dic[item]
    else:
        return [None]

In [8]:
print(len(chaiZi_Dic.keys()))
for item in "花丸A晴琉":
    print(getSubChar(item))
    print(xmnlp.radical(item))
    print()

14563
草 化
['艹']

丶 九
['丿']

[None]
[None]

日 青
['日']

玉 亠 厶 川
['王']



In [ ]:
# Preprocess the training and testing data.

In [104]:
pkuTrain = googlePath + "./corpus/cws/icwb2-data/training/pku_training.utf8"
pkuTest = googlePath + "./corpus/cws/icwb2-data/testing/pku_test.utf8"

f = open(pkuTest, "r")
temp = f.readlines()
con = 0
for item in temp:
    con+=1
    if(item == "\n"):
        print(con)

In [9]:
## Create Corpus for Chinese Word Segamentation

In [105]:
import pandas as pd
pkuTrain = googlePath + "./corpus/cws/icwb2-data/training/pku_training.utf8"
pkuTest = googlePath + "./corpus/cws/icwb2-data/testing/pku_test.utf8"
train = pd.read_table(pkuTrain,  encoding='utf8', header=None, names=['input'])  # don't drop the empty lines yet, they show up as NaN in the data frame
train.head(n=1)


input
0  迈向  充满  希望  的  新  世纪  ——  一九九八年  新年  讲话  （  附 ...

In [106]:
pkuTest = googlePath  + "./corpus/cws/icwb2-data/testing/pku_test.utf8"
test = pd.read_table(pkuTest,  encoding='utf8', header=None, names=['input']) 
test["raws"] = test["input"]
test.head(n=1)

input                   raws
0  共同创造美好的新世纪——二○○一年新年贺词  共同创造美好的新世纪——二○○一年新年贺词

In [107]:
def prepross_data(train_Data):
    inputs = train_Data["input"][:]
    print(len(inputs))
    raws = []
    tokenList = []
    
    for item in inputs:
        item = item.replace("   ", "  ")

        raw = item.replace(" ", "")
#         print(item)
#         print(raw)
        raws.append(raw)
        tokens = (item.split("  ")[:-1])
        tokenList.append(tokens)
#         print(tokens)
    train_Data["raws"] = raws
    train_Data["tokenList"] = tokenList
    dictionary_train_word = list(set(reduce(operator.add,train_Data["tokenList"])))
    dictionary_train_char =  list(set(reduce(operator.add,train_Data["raws"])))    
    return train_Data, dictionary_train_char, dictionary_train_word
train, train_dic_char, train_dic_word  = prepross_data(train)

19054


In [108]:
# Validate the pre-processing
def validate_data(data):
    tkList = data["tokenList"]
    raws = data["raws"]
    for (tokens, raw) in zip(tkList,raws):
#         print(tokens)
        
#         print(raw)
        temp  = "".join(tokens)
#         print(temp)
        assert(temp == raw)
        if not (temp == raw):
            print(temp)
            print(raw)
            print(tokens)
validate_data(train)

In [109]:
train.head(5)

input  \
0  迈向  充满  希望  的  新  世纪  ——  一九九八年  新年  讲话  （  附 ...   
1                      中共中央  总书记  、  国家  主席  江  泽民     
2                           （  一九九七年  十二月  三十一日  ）     
3  １２月  ３１日  ，  中共中央  总书记  、  国家  主席  江  泽民  发表  ...   
4           同胞  们  、  朋友  们  、  女士  们  、  先生  们  ：     

                                                raws  \
0                       迈向充满希望的新世纪——一九九八年新年讲话（附图片１张）   
1                                    中共中央总书记、国家主席江泽民   
2                                     （一九九七年十二月三十一日）   
3  １２月３１日，中共中央总书记、国家主席江泽民发表１９９８年新年讲话《迈向充满希望的新世纪》。...   
4                                   同胞们、朋友们、女士们、先生们：   

                                           tokenList  
0  [迈向, 充满, 希望, 的, 新, 世纪, ——, 一九九八年, 新年, 讲话, （, 附...  
1                      [中共中央, 总书记, 、, 国家, 主席, 江, 泽民]  
2                           [（, 一九九七年, 十二月, 三十一日, ）]  
3  [１２月, ３１日, ，, 中共中央, 总书记, 、, 国家, 主席, 江, 泽民, 发表,...  
4           [同胞, 们, 、, 朋友, 们, 、, 女士, 们, 、, 先生, 们, ：]

In [110]:
print(len(train_dic_char))
print(len(set(train_dic_char)))
print(len(train_dic_word))
print(len(set(train_dic_word)))
with open(googlePath + "./corpus/cws/icwb2-data/gold/pku_training_words.utf8", 'r') as f:
    content = f.readlines()  
    print(len(content))

4698
4698
55303
55303
55303


In [16]:
# Feature extraction

oov = len(train_dic_char)
print(oov)
def token_index(tok):
    ind = tok
    if tok in train_dic_char:  # if token in vocabulary
        ind = train_dic_char.index(tok)
    else:  # else it's OOV
        ind = oov
    return ind

def str_token_index(string):
    return [token_index(x)   for x in string]




# training labels: convert BIO to integers
# def bio_index(bio):
#     ind = bio
#     if not pd.isnull(bio):  # deal with empty lines
#         if bio=='B':
#             ind = 0
#         elif bio=='I':
#             ind = 1
#         elif bio=='O':
#             ind = 2
#     return ind

# Get Begin Middle End Single sequence
# B 0 M 1 E 2 S 3

def str_bmes_idx(tokenList):
    answer = []
    for item in tokenList:
        if len(item) == 0:
            raise NameErro("Zero Length Word")
        if len(item) == 1:
            answer.append(3)
        else:
            answer.append(0)
            for item in range(len(item) - 2):
                answer.append(1)
            answer.append(2)
    return answer




def extract_features(data_set, isTest=False):
    data_temp = data_set.copy()
    

    # Idx for chars
    with Pool(8) as p:
        tokinds = p.map(str_token_index,data_temp['raws'])
#     tokinds = [list(map(token_index, u)) for u in data_temp['raws']]
    data_temp["tokenIdx"] = tokinds
    
    # BIO
    if(not isTest):
        data_temp["bmes"] = [str_bmes_idx(u) for u in data_temp['tokenList']]
        assert (list(map(len,data_temp["bmes"])) == list(map(len,data_temp["tokenIdx"])))

        
#     print(data_temp["bmes"])
#    assert reduce(operator.and_, list(map(len,data_temp["bmes"])) == list(map(len,data_temp["tokenIdx"])))
    
    
    
    
    
    
    return data_temp
#     txt['token_indices'] = tokinds
#     if not istest:  # can't do this with the test set
#         bioints = [bio_index(b) for b in txt['bio_only']]
#         txt['bio_only'] = bioints
#     return txt

4698


In [61]:
%%time
# MultiThreading
train_feature = extract_features(train)
train_feature.head(5)

CPU times: user 422 ms, sys: 308 ms, total: 730 ms
Wall time: 15.3 s


input  \
0  迈向  充满  希望  的  新  世纪  ——  一九九八年  新年  讲话  （  附 ...   
1                      中共中央  总书记  、  国家  主席  江  泽民     
2                           （  一九九七年  十二月  三十一日  ）     
3  １２月  ３１日  ，  中共中央  总书记  、  国家  主席  江  泽民  发表  ...   
4           同胞  们  、  朋友  们  、  女士  们  、  先生  们  ：     

                                                raws  \
0                       迈向充满希望的新世纪——一九九八年新年讲话（附图片１张）   
1                                    中共中央总书记、国家主席江泽民   
2                                     （一九九七年十二月三十一日）   
3  １２月３１日，中共中央总书记、国家主席江泽民发表１９９８年新年讲话《迈向充满希望的新世纪》。...   
4                                   同胞们、朋友们、女士们、先生们：   

                                           tokenList  \
0  [迈向, 充满, 希望, 的, 新, 世纪, ——, 一九九八年, 新年, 讲话, （, 附...   
1                      [中共中央, 总书记, 、, 国家, 主席, 江, 泽民]   
2                           [（, 一九九七年, 十二月, 三十一日, ）]   
3  [１２月, ３１日, ，, 中共中央, 总书记, 、, 国家, 主席, 江, 泽民, 发表,...   
4           [同胞, 们, 、, 朋友, 们, 、, 女士, 们, 、, 先生, 们, ：]   

                                            tokenIdx  \
0  [2919, 4392, 4495, 726, 4078, 415, 3953, 186, ...   
1  [3296, 1046, 3296, 1933, 640, 3190, 1018, 2806...   
2  [4488, 4274, 2877, 2877, 2356, 4089, 3229, 337...   
3  [1897, 2078, 2209, 448, 1897, 2315, 1279, 3296...   
4  [858, 3372, 1236, 2806, 4371, 3772, 1236, 2806...   

                                                bmes  
0  [0, 2, 0, 2, 0, 2, 3, 3, 0, 2, 0, 2, 0, 1, 1, ...  
1      [0, 1, 1, 2, 0, 1, 2, 3, 0, 2, 0, 2, 3, 0, 2]  
2         [3, 0, 1, 1, 1, 2, 0, 1, 2, 0, 1, 1, 2, 3]  
3  [0, 1, 2, 0, 1, 2, 3, 0, 1, 1, 2, 0, 1, 2, 3, ...  
4   [0, 2, 3, 3, 0, 2, 3, 3, 0, 2, 3, 3, 0, 2, 3, 3]

In [18]:
def find_longest_sequence(data_with_features):
#     assert (np.max(list(map(len, data_with_features["tokenIdx"])))) == (np.max(list(map(len, data_with_features["bmes"]))))
    return (np.max(list(map(len, data_with_features["tokenIdx"]))))
    
    

In [19]:
%%time
temp = extract_features(test, isTest=True)
test_feature = temp
test_feature.head(5)

CPU times: user 14.2 ms, sys: 48.1 ms, total: 62.2 ms
Wall time: 1.76 s


input  \
0                              共同创造美好的新世纪——二○○一年新年贺词   
1                              （二○○○年十二月三十一日）（附图片1张）   
2                                   女士们，先生们，同志们，朋友们：   
3  2001年新年钟声即将敲响。人类社会前进的航船就要驶入21世纪的新航程。中国人民进入了向现代...   
4  在这个激动人心的时刻，我很高兴通过中国国际广播电台、中央人民广播电台和中央电视台，向全国各族...   

                                                raws  \
0                              共同创造美好的新世纪——二○○一年新年贺词   
1                              （二○○○年十二月三十一日）（附图片1张）   
2                                   女士们，先生们，同志们，朋友们：   
3  2001年新年钟声即将敲响。人类社会前进的航船就要驶入21世纪的新航程。中国人民进入了向现代...   
4  在这个激动人心的时刻，我很高兴通过中国国际广播电台、中央人民广播电台和中央电视台，向全国各族...   

                                            tokenIdx  
0  [1046, 858, 37, 3118, 3328, 4588, 3953, 186, 3...  
1  [4488, 3376, 2295, 2295, 2295, 4089, 3229, 337...  
2  [1896, 1480, 1236, 1279, 2547, 4104, 1236, 127...  
3  [1597, 2789, 2789, 1621, 4089, 186, 4089, 1728...  
4  [3337, 1996, 1632, 3006, 1158, 2566, 817, 3953...

In [20]:

train_longest = find_longest_sequence(train_feature)
print(train_longest)

test_longest = find_longest_sequence(test_feature)
print(test_longest)

seq_longest = np.max([train_longest,test_longest])
print(seq_longest)


1019
626
1019


In [21]:
seq_length = seq_longest

# a new dummy token index, one more than OOV
padtok = oov+1
print('The padding token index is %i' % padtok)

# use pad_sequences, padding or truncating at the end of the sequence (default is 'pre')
train_seqs_padded = pad_sequences(train_feature['tokenIdx'].tolist(), maxlen=seq_length,
                                  dtype='int32', padding='post', truncating='post', value=padtok)
print('Example of padded token sequence:')
print(train_seqs_padded[1])

# Prepare Test set.
seq_length = seq_longest
padtok = oov+1

test_seqs_padded = pad_sequences(test_feature['tokenIdx'].tolist(), maxlen=seq_length,
                                  dtype='int32', padding='post', truncating='post', value=padtok)

The padding token index is 4699
Example of padded token sequence:
[3296 1046 3296 ... 4699 4699 4699]


In [22]:
from keras.utils import to_categorical

# get lists of named entity labels, padded with a null label (=3)
padlab = 4
train_labs_padded = pad_sequences(train_feature['bmes'].tolist(), maxlen=seq_length,
                                  dtype='int32', padding='post', truncating='post', value=padlab)

# convert those labels to one-hot encoding
n_labs = 5
train_labs_onehot = [to_categorical(i, num_classes=n_labs) for i in train_labs_padded]

# follow the print outputs below to see how the labels are transformed
print('Length of input sequence: %i' % len(train_labs_padded[1]))
print('Length of label sequence: %i' % len(train_labs_onehot[1]))
print(train_labs_padded[1][:11])
print(train_labs_onehot[1][:11])

Length of input sequence: 1019
Length of label sequence: 1019
[0 1 1 2 0 1 2 3 0 2 0]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [32]:
# load Keras and TensorFlow
from tensorflow import keras
import tensorflow as tf

# prepare sequences and labels as numpy arrays, check dimensions
X = np.array(train_seqs_padded)
y = np.array(train_labs_onehot)
print('Input sequence dimensions (n.docs, seq.length):')
print(X.shape)
print('Label dimensions (n.docs, seq.length, one-hot encoding of 4 NER labels):')
print(y.shape)

# our final vocab size is the padding token + 1 (OR length of vocab + OOV + PAD)
vocab_size = padtok+1
print(vocab_size==len(train_dic_char)+2)
embed_size = 128 # y an embedding size of 128 (could tune this)

# list of metrics to use: true & false positives, negatives, accuracy, precision, recall, area under the curve
METRICS = [
      keras.metrics.TruePositives(name='tp'),
      keras.metrics.FalsePositives(name='fp'),
      keras.metrics.TrueNegatives(name='tn'),
      keras.metrics.FalseNegatives(name='fn'), 
      keras.metrics.BinaryAccuracy(name='accuracy'),
      keras.metrics.Precision(name='precision'),
      keras.metrics.Recall(name='recall'),
      keras.metrics.AUC(name='auc'),
]

# our model has the option for an label prediction bias, it's sequential, starts with an embedding layer, then bi-LSTM,
# a dropout layer follows for regularisation, and a dense final layer with softmax activation to output class probabilities
# we compile with the Adam optimizer at a low learning rate, use categorical cross-entropy as our loss function
def make_model(metrics = METRICS, output_bias=None):
    if output_bias is not None:
        output_bias = tf.keras.initializers.Constant(output_bias)
    model = keras.Sequential([
        keras.layers.Embedding(input_dim=vocab_size, output_dim=embed_size, input_length=seq_length, mask_zero=True, trainable=True),
        keras.layers.Bidirectional(keras.layers.LSTM(units=50, return_sequences=True, dropout=0.2)),  # 2 directions, 50 units each, concatenated (can change this)
#         keras.layers.Bidirectional(keras.layers.LSTM(units=50, return_sequences=True, dropout=0.2, recurrent_dropout=0.2)),  # 2 directions, 50 units each, concatenated (can change this)
        keras.layers.Dropout(0.5),
        keras.layers.TimeDistributed(keras.layers.Dense(n_labs, activation='softmax', bias_initializer=output_bias)),
    ])
    model.compile(optimizer=keras.optimizers.Adam(lr=1e-3), loss=keras.losses.CategoricalCrossentropy(), metrics=metrics)
    return model

# early stopping criteria based on area under the curve: will stop if no improvement after 10 epochs
early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_auc', verbose=1, patience=10, mode='max', restore_best_weights=True)

# the number of training epochs we'll use, and the batch size (how many texts are input at once)
EPOCHS = 100
BATCH_SIZE = 128

print('**Defining a neural network**')
model = make_model()
model.summary()

Input sequence dimensions (n.docs, seq.length):
(19054, 1019)
Label dimensions (n.docs, seq.length, one-hot encoding of 4 NER labels):
(19054, 1019, 5)
True
**Defining a neural network**
Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_7 (Embedding)      (None, 1019, 128)         601600    
_________________________________________________________________
bidirectional_7 (Bidirection (None, 1019, 100)         71600     
_________________________________________________________________
dropout_7 (Dropout)          (None, 1019, 100)         0         
_________________________________________________________________
time_distributed_7 (TimeDist (None, 1019, 5)           505       
Total params: 673,705
Trainable params: 673,705
Non-trainable params: 0
_________________________________________________________________


In [27]:
# %%time
# # evaluate our initial model
# results = model.evaluate(X, y, batch_size=BATCH_SIZE, verbose=0)
# print("Loss: {:0.4f}".format(results[0]))

In [28]:
# figure out the label distribution in our fixed-length texts
from collections import Counter

all_labs = [l for lab in train_labs_padded for l in lab]
label_count = Counter(all_labs)
total_labs = len(all_labs)
print(label_count)
print(total_labs)

# use this to define an initial model bias
initial_bias=[(label_count[0]/total_labs), (label_count[1]/total_labs),
              (label_count[2]/total_labs), (label_count[3]/total_labs), (label_count[4]/total_labs)]
print('Initial bias:')
print(initial_bias)

# # pass the bias to the model and re-evaluate
# model = make_model(output_bias=initial_bias)
# results = model.evaluate(X, y, batch_size=BATCH_SIZE, verbose=0)
# print("Loss: {:0.4f}".format(results[0]))

Counter({4: 17589578, 0: 585226, 2: 585226, 3: 524721, 1: 131275})
19416026
Initial bias:
[0.03014138938627297, 0.006761167295511451, 0.03014138938627297, 0.027025149224666263, 0.9059309047072763]


In [ ]:
%%time
# re-initiate model with bias
model = make_model(output_bias=initial_bias)

# and fit...
model.fit(X, y, batch_size=BATCH_SIZE, epochs=10, callbacks = [early_stopping],  validation_split = 0.3)

Train on 13337 samples, validate on 5717 samples
Epoch 1/10
13337/13337 [==============================] - 155s 12ms/sample - loss: 0.2262 - tp: 11499978.0000 - fp: 42462.0000 - tn: 54318732.0000 - fn: 2090320.0000 - accuracy: 0.9686 - precision: 0.9963 - recall: 0.8462 - auc: 0.9957 - val_loss: 0.1141 - val_tp: 5292816.0000 - val_fp: 1181.0000 - val_tn: 23301084.0000 - val_fn: 532751.0000 - val_accuracy: 0.9817 - val_precision: 0.9998 - val_recall: 0.9085 - val_auc: 0.9986
Epoch 2/10
13337/13337 [==============================] - 152s 11ms/sample - loss: 0.1027 - tp: 12593099.0000 - fp: 107597.0000 - tn: 54253596.0000 - fn: 997199.0000 - accuracy: 0.9837 - precision: 0.9915 - recall: 0.9266 - auc: 0.9986 - val_loss: 0.0769 - val_tp: 5557205.0000 - val_fp: 48897.0000 - val_tn: 23253372.0000 - val_fn: 268362.0000 - val_accuracy: 0.9891 - val_precision: 0.9913 - val_recall: 0.9539 - val_auc: 0.9993
Epoch 3/10
  512/13337 [>.............................] - ETA: 1:38 - loss: 0.0853 - tp: 4

In [111]:
X_test = np.array(test_seqs_padded)
# preds = np.argmax(model.predict(X_test), axis=-1)
preds = np.argmax(model.predict(X_test), axis=-1)
flat_preds = [p for pred in preds for p in pred]
print(Counter(flat_preds))

Counter({4: 1809127, 2: 64042, 0: 59501, 3: 47181, 1: 1085})


In [112]:
len(preds)

1944

In [113]:
def postEditPred(pred):
    print(pred)
    ans = []
    for item in pred:
        if item == 0 or item == 3:
            ans.append(1)
        else:
            ans.append(0)
            
    assert len(ans) == len(pred)
    return ans

def splitSentence(st, pred):
    temp_st = st
    temp_pred = pred
    temp_pred[0] = 2
    buf = []
    result = []
    for (pre,char) in zip(temp_pred,temp_st):
        if(pre == 0 or pre == 3):
            result.append(buf)
            buf = []
        buf.append(char)
    if(len(buf) > 0):
        result.append(buf)
    return result
    
    



def sentencePrediction(dataset,prediction):
    data_temp = dataset.copy()
    assert len(data_temp) == len(prediction)
    raw_sents = data_temp["raws"]
    assert len(raw_sents) == len(prediction)
    ans = []
    for (st,pred) in zip(raw_sents,prediction):
        sptSt = splitSentence(st,pred)
        ans.append(sptSt)
    assert len(ans) == len(data_temp)
    data_temp["tokenList"]= ans
    return data_temp
    
def convertToPredSts(dataset):
    data_temp = dataset.copy()
    tokenList = data_temp["tokenList"]
    ans = []
    
    for item in tokenList:
        temp_st = list(map(lambda x : "".join(x), item))
        temp = "  ".join(temp_st)
        temp = temp + "  "
        ans.append(temp)
    return ans

In [114]:
    
    
result_pred = sentencePrediction(test_feature,preds)
output_sts = convertToPredSts(result_pred)

f = open("./ans.txt", "w")
f.write("\n".join(output_sts))
f.close()

In [85]:
output_sts[452] == train_feature["input"][452]

True

In [95]:
for con in range(len(output_sts)):
    if not output_sts[con] == train_feature["input"][con].replace("   ", "  "):
        print()
        print(train_feature["input"][con])
        
        print(output_sts[con])
        print()
        print()

In [94]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())


[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 13195449856465368577
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 11182983223473196045
physical_device_desc: "device: XLA_CPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 5601390752
locality {
  bus_id: 1
  links {
  }
}
incarnation: 10248998340463966654
physical_device_desc: "device: 0, name: GeForce GTX 1660 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 11306986678221424848
physical_device_desc: "device: XLA_GPU device"
]


In [ ]:
sess = tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(log_device_placement=True))